### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blugon/current'

### ISSUE THREAD

**Issue by howaboutsynergy** [jumper149/blugon#5]
```
$ /usr/bin/blugon -r
Traceback (most recent call last):
  File "/usr/bin/blugon", line 327, in read_current
    file_current = open(CONFIG_FILE_CURRENT, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blugon/current'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/blugon", line 555, in <module>
    main()
  File "/usr/bin/blugon", line 486, in main
    CURRENT = read_current()
  File "/usr/bin/blugon", line 331, in read_current
    'To create this file use:\n' + '    blugon --setcurrent=' + str(NORMAL_TEMP))
ValueError: current configuration file not found at:
    /home/user/.config/blugon/current

To create this file use:
    blugon --setcurrent=6600.0
```

```
$ /usr/bin/blugon -p
[main]
readcurrent = False
interval = 120
backend = scg
wait_for_x = False
fade = False

[current]
min_temp = 1.0
max_temp = 20000.0

[wait_for_x]
sleep_after_failed_startup = 0.1
sleep_after_losing_x = 120.0

[fade]
steps = 10
duration = 3.0

[tty]
color0 = 000000
color1 = aa0000
color2 = 00aa00
color3 = aa5500
color4 = 0000aa
color5 = aa00aa
color6 = 00aaaa
color7 = aaaaaa
color8 = 555555
color9 = ff5555
color10 = 55ff55
color11 = ffff55
color12 = 5555ff
color13 = ff55ff
color14 = 55ffff
color15 = ffffff

```

```
$ blugon -V
Using gamma configuration file: '/home/user/.config/blugon/gamma'
Using fallback gamma configuration file: '/usr/share/blugon/configs/default/gamma'
Provide current minute 54.35
Calculated RGB Gamma values: 1.0 0.806038888888889 0.5701296296296297
Calling backend scg
Wait for 120 seconds
```

commit a77a20226e2933576b66e5f08ed1f6a420cdbf3e (HEAD -> makepkg, origin/master, origin/HEAD, master)

**Comment by howaboutsynergy** [comment]
```
  -r, --readcurrent     read temperature from
                        /home/user/.config/blugon/current
```

nevermind, I misunderstood what `-r` does!
I thought it shows me the current config

**Comment by howaboutsynergy** [comment]
It won't create it (parent dirs?)

```
$ blugon --setcurrent=6600.0
Traceback (most recent call last):
  File "/usr/bin/blugon", line 555, in <module>
    main()
  File "/usr/bin/blugon", line 483, in main
    set_current()
  File "/usr/bin/blugon", line 367, in set_current
    with open(CONFIG_FILE_CURRENT, 'w') as file_current:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blugon/current'
```

```
$ l /home/user/.config/blugon/
ls: cannot access '/home/user/.config/blugon/': No such file or directory
```

**Comment by jumper149** [comment]
I don't want the program to mess around in someones home directory without them knowing about it, thats why I want the user to create the directory with `mkdir`. I am adding it to the man page which doesn't have it at the moment.

**Comment by howaboutsynergy** [comment]
In truth, I kinda expect it to create the parent dirs also, after it said this:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/blugon/current'
...
ValueError: current configuration file not found at:
    /home/user/.config/blugon/current

To create this file use:
    blugon --setcurrent=6600.0
```

**Comment by jumper149** [comment]
Ok, I also added a sanity check (5e58cf9af9b5b772fec110a8321bcc282ee5484b), which let's the user know when the config directory doesn't exist.

**Comment by howaboutsynergy** [comment]
pretty cool then, cheers
